---
title: "Modeling Assumptions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
```

```{r}
# import data
modeling_data_province <- read.csv(file = "https://raw.githubusercontent.com/francomomo/datafest-2020/master/data/cleaned_data/modeling_data_province.csv")
head(modeling_data_province)
```

## MLR
```{r}
model <- lm(Score ~ New.Cases + New.Deaths + Mean.Temperature + Total.Precipitation + New.Cases..world. + New.Deaths..world. + Days.Since.First.Case, data = modeling_data_province)
summary(model)
```

## Leverage Points
```{r}
h <- hatvalues(model)
thresh <- 2 * (dim(model.matrix(model))[2])/nrow(modeling_data_province)
w <- which(h > thresh)
w
modeling_data_province[w,]
```

## Influential Observations
```{r}
# Observations
n <- 695

# Predictors
p <- 7

# Cooks' Distance
D <- cooks.distance(model)
which(D > qf(0.5, p + 1, n - p - 1))

# DFFITS
dfits <- dffits(model)
which(abs(dfits) > 2*sqrt((p + 1)/n))

# DFBETAS
dfb <- dfbetas(model)
which(abs(dfb[,1]) > 2/sqrt(n))
```

## Check Assumptions
```{r}
resid <- rstudent(model)
fitted <- predict(model)

# Normal QQ Plot and Standardized Residuals Plot
par(family = 'serif', mfrow = c(1,2))
qqnorm(resid)
qqline(resid)
plot(resid ~ fitted, type = "p", xlab = "Fitted Values", 
     ylab = "Standardized Residual", cex.lab = 1.2,
     col = "red")
lines(lowess(fitted, resid), col = "blue")
# abline(lm(resid ~ fitted), lwd = 2, col = "blue")

# Response vs Fitted values
par(family = 'serif')
plot(modeling_data_province$Score ~ fitted, type = "p", xlab = "Fitted Values", 
     ylab = "Score", cex.lab = 1.2,
     col = "red")
abline(lm(modeling_data_province$Score ~ fitted), lwd = 2, col = "blue")
lines(lowess(fitted, modeling_data_province$Score), col = "red")
```











